Controllers/API/CustomerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using AutoMapper;
using MovieRental.Dtos;
using System.Data.Entity;
using MovieRental.Models;

namespace MovieRental.Controllers.API
{
    public class CustomerController : ApiController
    {
        private MyDbContext _context;

        public CustomerController()
        {
            _context = new MyDbContext();
        }

        //GET /api/customer
        [HttpGet]
        public IEnumerable<CustomerDto> GetAll()
        {
            return _context.Customers.Include(c => c.MembershipType).ToList().Select(m => Mapper.Map<Customer, CustomerDto>(m)).ToList(); 
        }

        //GET /api/customer/1
        [HttpGet]
        public CustomerDto Get(int id)
        {
            var customer = _context.Customers.Include(c => c.MembershipType).ToList().SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Mapper.Map<Customer, CustomerDto>(customer);
        }

        //POST api/customer
        [HttpPost]
        public CustomerDto Add(CustomerDto customerDto)
        {
            if(!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            _context.Customers.Add(customer);
            _context.SaveChanges();

            customerDto.Id = customer.Id;
            customer.MembershipType = _context.MembershipTypes.SingleOrDefault(c => c.Id == customer.MembershipTypeId);
            customerDto.MembershipType = Mapper.Map<MembershipType, MembershipTypeDto>(customer.MembershipType);
            return customerDto;
        }

        //PUT api/customer/1
        [HttpPut]
        public CustomerDto Update(int id , CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customerInDb = _context.Customers.Include(c => c.MembershipType).ToList().SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

           Mapper.Map<CustomerDto, Customer>(customerDto, customerInDb);

            /* if (!string.IsNullOrEmpty(customerDto.Name) && !customerDto.Name.Equals(customerInDb.Name))
                customerInDb.Name = customerDto.Name;

            if (customerDto.MembershipTypeId != cus tomerInDb.MembershipTypeId)
            {
                customerInDb.MembershipTypeId = customerDto.MembershipTypeId;
            }
         
            if (!string.IsNullOrEmpty(customerDto.Email) && !customerDto.Email.Equals(customerInDb.Email))
                customerInDb.Email = customerDto.Email;

            if (customerDto.IsSubscribedToNewsLetter!=customerInDb.IsSubscribedToNewsLetter)
                customerInDb.IsSubscribedToNewsLetter = customerDto.IsSubscribedToNewsLetter;

            if (customerDto.BirthDate != customerInDb.BirthDate)
                customerInDb.BirthDate = customerDto.BirthDate;
*/
            _context.SaveChanges();
            customerInDb.MembershipType = _context.MembershipTypes.SingleOrDefault(c => c.Id == customerInDb.MembershipTypeId);
            customerDto.MembershipType = Mapper.Map<MembershipType, MembershipTypeDto>(customerInDb.MembershipType);
            return customerDto;
        }

        //DELETE api/customer/1
        [HttpDelete]
  
        public void Delete(int id)
        {
            var customer = _context.Customers.Single(m => m.Id == id);
            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Customers.Remove(customer);

            _context.SaveChanges();
        }
    }
}

Controllers/API/MovieController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using AutoMapper;
using MovieRental.Dtos;
using MovieRental.Models;
using System.Data.Entity;

namespace MovieRental.Controllers.API
{
    public class MovieController : ApiController
    {
        private MyDbContext _context;

        public MovieController()
        {
            _context = new MyDbContext();
        }

        //GET /movie/getall
        [HttpGet]
        public IEnumerable<MovieDto> GetAll()
        {
            return _context.Movies.Include(c => c.Genre).ToList().Select(m => Mapper.Map<Movie, MovieDto>(m)).ToList();
        }

        //GET /movie/get/1
        [HttpGet]
        public MovieDto Get(int id)
        {
            var movie = _context.Movies.Include(c => c.Genre).ToList().SingleOrDefault(c => c.Id == id);

            if (movie == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Mapper.Map<Movie, MovieDto>(movie);
        }

        //POST /movie/new
        [HttpPost]
        public MovieDto Add(MovieDto movieDto)
        {
            if(!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;
            return movieDto;
        }

        //PUT /movie/update
        [HttpPut]
        public MovieDto Update(int id , MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var movieInDb = _context.Movies.Include(c => c.Genre).ToList().SingleOrDefault(c => c.Id == id);

            if (movieInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

           Mapper.Map<MovieDto, Movie>(movieDto, movieInDb);

            /*if (!string.IsNullOrEmpty(movieDto.Name) && !movieDto.Name.Equals(movieInDb.Name))
                movieInDb.Name = movieDto.Name;

            if (movieDto.GenreId != movieInDb.GenreId)
            {
                movieInDb.GenreId = movieDto.GenreId;
            }
            if (movieDto.NumberOfStock !=  movieInDb.NumberOfStock)
                movieInDb.NumberOfStock = movieDto.NumberOfStock;

            if (movieDto.ReleaseDate != movieInDb.ReleaseDate)
                movieInDb.ReleaseDate = movieDto.ReleaseDate;
*/
            _context.SaveChanges();

            return movieDto;
        }

        //DELETE /movie/delete/1
        [HttpDelete]
  
        public void Delete(int id)
        {
            var movie = _context.Movies.Single(m => m.Id == id);
            if (movie == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Movies.Remove(movie);

            _context.SaveChanges();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRental</title>

    <link rel="stylesheet" href="~/css/bootstrap-lumen.css" />
    <link rel="stylesheet" href="~/css/custom/site.css" />
    <link rel="stylesheet" href="~/css/common.scss" />

    <link rel="stylesheet" href="~/css/autoFill.bootstrap.css" />
    <link rel="stylesheet" href="~/css/autoFill.dataTables.css" />
    <link rel="stylesheet" href="~/css/autoFill.foundation.css" />
    <link rel="stylesheet" href="~/css/autoFill.jqueryui.css" />

    <link rel="stylesheet" href="~/css/buttons.bootstrap.css" />
    <link rel="stylesheet" href="~/css/buttons.bootstrap4.css" />
    <link rel="stylesheet" href="~/css/buttons.dataTables.css" />
    <link rel="stylesheet" href="~/css/buttons.foundation.css" />
    <link rel="stylesheet" href="~/css/buttons.jqueryui.css" />

    <link rel="stylesheet" href="~/css/colReorder.bootstrap.css" />
    <link rel="stylesheet" href="~/css/colReorder.dataTables.css" />
    <link rel="stylesheet" href="~/css/colReorder.foundation.css" />
    <link rel="stylesheet" href="~/css/colReorder.jqueryui.css" />

    <link rel="stylesheet" href="~/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/css/dataTables.bootstrap.css" />
    <link rel="stylesheet" href="~/css/dataTables.foundation.css" />
    <link rel="stylesheet" href="~/css/dataTables.jqueryui.css" />
    <link rel="stylesheet" href="~/css/dataTables.material.css" />
    <link rel="stylesheet" href="~/css/dataTables.semanticui.css" />
    <link rel="stylesheet" href="~/css/dataTables.uikit.css" />

    <link rel="stylesheet" href="~/css/fixedColumns.bootstrap.css" />
    <link rel="stylesheet" href="~/css/fixedColumns.dataTables.css" />
    <link rel="stylesheet" href="~/css/fixedColumns.foundation.css" />
    <link rel="stylesheet" href="~/css/fixedColumns.jqueryui.css" />

    <link rel="stylesheet" href="~/css/fixedHeader.bootstrap.css" />
    <link rel="stylesheet" href="~/css/fixedHeader.dataTables.css" />
    <link rel="stylesheet" href="~/css/fixedHeader.foundation.css" />
    <link rel="stylesheet" href="~/css/fixedHeader.jqueryui.css" />

    <link rel="stylesheet" href="~/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="~/css/jquery.dataTables_themeroller.css" />

    <link rel="stylesheet" href="~/css/keyTable.bootstrap.css" />
    <link rel="stylesheet" href="~/css/keyTable.dataTables.css" />
    <link rel="stylesheet" href="~/css/keyTable.foundation.css" />
    <link rel="stylesheet" href="~/css/keyTable.jqueryui.css" />

    <link rel="stylesheet" href="~/css/responsive.bootstrap.css" />
    <link rel="stylesheet" href="~/css/responsive.dataTables.css" />
    <link rel="stylesheet" href="~/css/responsive.foundation.css" />
    <link rel="stylesheet" href="~/css/responsive.jqueryui.css" />

    <link rel="stylesheet" href="~/css/rowReorder.bootstrap.css" />
    <link rel="stylesheet" href="~/css/rowReorder.dataTables.css" />
    <link rel="stylesheet" href="~/css/rowReorder.foundation.css" />
    <link rel="stylesheet" href="~/css/rowReorder.jqueryui.css" />

    <link rel="stylesheet" href="~/css/scroller.bootstrap.css" />
    <link rel="stylesheet" href="~/css/scroller.dataTables.css" />
    <link rel="stylesheet" href="~/css/scroller.foundation.css" />
    <link rel="stylesheet" href="~/css/scroller.jqueryui.css" />

    <link rel="stylesheet" href="~/css/select.bootstrap.css" />
    <link rel="stylesheet" href="~/css/select.dataTables.css" />
    <link rel="stylesheet" href="~/css/select.foundation.css" />
    <link rel="stylesheet" href="~/css/select.jqueryui.css" />

</head>
<body>
    @Html.Partial("_NavBar");
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.dataTables.js"></script>

    <script src="~/js/additional-methods.js"></script>

    <script src="~/js/autoFill.bootstrap.js"></script>
    <script src="~/js/autoFill.foundation.js"></script>
    <script src="~/js/autoFill.jqueryui.js"></script>

    <script src="~/js/dataTables.autoFill.js"></script>
    <script src="~/js/dataTables.bootstrap4.js"></script>
    <script src="~/js/dataTables.bootstrap.js"></script>

    <script src="~/js/dataTables.buttons.js"></script>
    <script src="~/js/dataTables.colReorder.js"></script>
    <script src="~/js/dataTables.fixedColumns.js"></script>
    <script src="~/js/dataTables.fixedHeader.js"></script>
    <script src="~/js/dataTables.foundation.js"></script>
    <script src="~/js/dataTables.jqueryui.js"></script>
    <script src="~/js/dataTables.keyTable.js"></script>

    <script src="~/js/dataTables.material.js"></script>
    <script src="~/js/dataTables.responsive.js"></script>
    <script src="~/js/dataTables.rowReorder.js"></script>
    <script src="~/js/dataTables.scroller.js"></script>
    <script src="~/js/dataTables.select.js"></script>
    <script src="~/js/dataTables.semanticui.js"></script>
    <script src="~/js/dataTables.uikit.js"></script>

    <script src="~/js/responsive.bootstrap.js"></script>
    <script src="~/js/responsive.foundation.js"></script>
    <script src="~/js/responsive.jqueryui.js"></script>

    <script src="~/js/buttons.bootstrap.js"></script>
    <script src="~/js/buttons.bootstrap4.js"></script>
    <script src="~/js/buttons.colVis.js"></script>
    <script src="~/js/buttons.flash.js"></script>
    <script src="~/js/buttons.foundation.js"></script>
    <script src="~/js/buttons.html5.js"></script>
    <script src="~/js/buttons.jqueryui.js"></script>
    <script src="~/js/buttons.print.js"></script>

    <script src="~/js/autoFill.foundation.js"></script>
    <script src="~/js/autoFill.bootstrap.js"></script>
    <script src="~/js/autoFill.jqueryui.js"></script>

    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootbox.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
 <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
       <div class="container">
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
           <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
               <h1>Movie Rental</h1>
               <ul class="navbar-nav flex-grow-1">
                   <li>
                       <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                   </li>
                   <li>
                       @Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
                   </li>
                   <li>
                       @Html.ActionLink("Movies", "Index", "Movie", new { area = "" }, new { @class = "navbar-brand" })
                   </li>
               </ul>
           </div>
       </div>
 </nav>